#!/bin/bash

set -e

VERSION="1.0.0"
RELEASE_DIR=`pwd`/tocc-$VERSION

rm -rf $RELEASE_DIR
mkdir $RELEASE_DIR

echo "Getting source..."
rm -rf tocc/
git clone --depth=1 https://github.com/aidin36/tocc.git

echo "Copying files..."
cp tocc/AUTHORS tocc/CHANGELOG tocc/CHANGELOG tocc/CONTRIBUTING tocc/COPYING tocc/README.md $RELEASE_DIR

rsync -av --exclude='docs/' tocc/libtocc/ $RELEASE_DIR/libtocc
rsync -av --exclude='docs/' tocc/cli/ $RELEASE_DIR/cli/
rsync -av --exclude='docs/' tocc/toccfs/ $RELEASE_DIR/toccfs/

echo "Configuring..."
cd $RELEASE_DIR/libtocc/src/
./bootstrap
rm -rf autom4te.cache
for link_file in *; do
   if [[ -L $link_file ]]; then
      true_file=`readlink $link_file`;
      rm $link_file;
      cp $true_file .;
   fi
done

cd ../tests/
./bootstrap
rm -rf autom4te.cache
for link_file in *; do
   if [[ -L $link_file ]]; then
      true_file=`readlink $link_file`;
      rm $link_file;
      cp $true_file .;
   fi
done

cd ../../cli/src/
./bootstrap
rm -rf autom4te.cache
for link_file in *; do
   if [[ -L $link_file ]]; then
      true_file=`readlink $link_file`;
      rm $link_file;
      cp $true_file .;
   fi
done

cd ../../toccfs/src/
./bootstrap
rm -rf autom4te.cache
for link_file in *; do
   if [[ -L $link_file ]]; then
      true_file=`readlink $link_file`;
      rm $link_file;
      cp $true_file .;
   fi
done

echo "Making docs..."
cd ../../../tocc/docs/
make html
rm -r build/html/_sources/
mkdir $RELEASE_DIR/docs/
cp -r build/html/* $RELEASE_DIR/docs/

cd ../libtocc/docs/
make html
rm -r build/html/_sources/
mkdir $RELEASE_DIR/libtocc/docs/
cp -r build/html/* $RELEASE_DIR/libtocc/docs/

cd ../../cli/docs/
make html
rm -r build/html/_sources/
mkdir $RELEASE_DIR/cli/docs/
cp -r build/html/* $RELEASE_DIR/cli/docs/

cd ../../toccfs/docs/
make html
rm -r build/html/_sources/
mkdir $RELEASE_DIR/toccfs/docs/
cp -r build/html/* $RELEASE_DIR/toccfs/docs/

cd ../../../

echo "Packaging..."
tar czf tocc-"$VERSION".tar.gz tocc-$VERSION

echo "Done :-)"

